apiVersion: apps/v1          # Версия API Kubernetes, определяющая правила для ресурса
kind: Deployment             # Тип создаваемого ресурса — управляющий контроллер Деплоймент
metadata:                    # Метаданные самого Деплоймента (имя, настройки, системные маркеры)
  name: my-web-app           # Уникальное имя этого Деплоймента в текущем пространстве имен
spec:                        # Спецификация — описание желаемого состояния всей группы Подов
  replicas: 1                # Количество идентичных копий (Подов), которое K8s обязан поддерживать
  selector:                  # Настройки фильтра, указывающие, какими именно Подами управлять
    matchLabels:             # Список меток (тегов) для поиска «своих» Подов
      app: frontend          # Деплоймент управляет только теми Подами, у которых есть этот тег
  template:                  # Шаблон (чертеж), по которому будут создаваться новые Поды
    metadata:                # Метаданные для каждого нового Пода, созданного по этому шаблону
      labels:                # Метки, которые автоматически наклеиваются на каждый новый Под
        app: frontend        # Тег Пода (обязан совпадать с matchLabels выше, чтобы связь работала)
    spec:                    # Спецификация внутренностей Пода (какие контейнеры в нем живут)
      containers:            # Список контейнеров, которые запустятся внутри Пода
      - name: flask-app          # Имя конкретного контейнера в Поде
        image: registry.gitlab.com/polyakovpavell/devops-final-project:latest  # Ссылка на Docker-образ и его тег (версию) для скачивания