[runner]
89.169.148.232

[k8s]
62.84.116.94

[all:vars]
# Пользователь, под которым заходим на сервер
ansible_user=ubuntu

# Отключаем интерактивный вопрос "Are you sure you want to continue connecting?"
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

# Явно указываем, какой приватный SSH-ключ использовать
ansible_ssh_private_key_file=~/.ssh/id_ed25519