---
# БЛОК 1: PLAY (Сценарий)
# Здесь мы привязываем группу серверов к задачам
- name: Установка Docker
  hosts: all  # Указываем группу из файла hosts.ini
  become: yes        # Даем команду выполнять всё через sudo (права root)

  # БЛОК 2: TASKS (Задачи)
  # Список того, что нужно сделать на серверах
  tasks:

    - name: Шаг первый — Обновить кеш пакетов
      apt:            # Вызов специализированного модуля apt
        update_cache: yes

    - name: Шаг второй — Установить докер
      apt:            # Снова используем модуль apt
        name: docker.io